{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "influxdb-srelay.fullname" . }}
  labels:
    app: {{ template "influxdb-srelay.fullname" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  cert.pem: {{ .Values.tls.cert | b64enc }}
  key.pem: {{ .Values.tls.key | b64enc }}
{{- end }}