apiVersion: v1
kind: Service
metadata:
  name: {{ template "dble.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "dble.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{- if .Values.service.annotations }}
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
  - name: dble
    port: {{ .Values.service.dble.port |default 8066 }}
    targetPort: dble
    {{- if .Values.service.dble.nodePort }}
    nodePort: {{ .Values.service.dble.nodePort }}
    {{- end }}
  - name: admin
    port: {{ .Values.service.admin.port |default 9066 }}
    targetPort: dble
    {{- if .Values.service.admin.nodePort }}
    nodePort: {{ .Values.service.admin.nodePort }}
    {{- end }}
  selector:
    app: {{ template "dble.fullname" . }}
